<?php
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/friends.css");
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/msg.css");
?>

<?php if(is_string($this->data)) { ?>
	<div id="content1"><?php echo $this->data; ?></div> 
<?php } else { ?>
<?php for($i=0;$i<count($this->data);$i++) { ?>
   <div class ="spl">
        <?php if (!empty($this->profile[$i]['photo'])) { ?>
        <img src ="<?php echo IMAGE_PATH ?>/<?php echo $this->profile[$i]['photo'] ?>" >
                <?php } else { ?>
                    <img class="avatar border-gray" src="<?php echo IMAGE_PATH ?>/static/default-avatar.png" alt=""/> 
                    <?php } ?>
       <div class ="username"><?php echo $this->data[$i]->getUsername() ?></div>
       <div class ="email"><?php echo $this->data[$i]->getEmailId() ?></div>
       <a href="confirm/id/<?php echo $this->data[$i]->getId() ?>"><button class="butn">Confirm</button></a>
       <a href="decline/id/<?php echo $this->data[$i]->getId() ?>"><button class="butn">Not Now</button></a>
   </div>
 <?php } ?>
<?php } ?>