<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<style>
			
			.spl {
			    width: 282px;
			    height: 178px;
			    float:left;
			    margin-right: 15px;
			    border-color: #9B9590
			    
			}
			.spl img {
			    border-radius: 35px;
			    width: 136px;
			    margin-left: 13px;
			    height: 90px;
			}
			.username{
			    margin-left: 41px;
			}
			.email{
			    margin-left: 43px;
			}
			.butn{
			    font-size: inherit;
			    margin-left: 15px;
			}
		</style>
	</head>
	<body>
		
			
				<div class ="spl">
					<img src ="avatar border-gray" src="<?php echo IMAGE_PATH ?>/static/faces/face-3.jpg" >
					<div class = "username">Raghav
					</div>
					<div class = "email">Goyal
					</div>
					
						<a href=""><button class="butn" id="btnsubmit">Accept</button></a>
						<a href=""><button class="butn" id="btnsubmit">Decline</button></a>
					
				</div>
			
		
	</body>
</html>