<!DOCTYPE html>
<html>
	<head>
		<title></title>
		<style>
			
			.spl {
			    width: 282px;
			    height: 178px;
			    float:left;
			    margin-right: 15px;
			    border-color: #9B9590
			    
			}
			.spl img {
			    border-radius: 35px;
			    width: 136px;
			    margin-left: 13px;
			    height: 90px;
			}
			.username{
			    margin-left: 41px;
			}
			.email{
			    margin-left: 43px;
			}
			.butn{
			    font-size: inherit;
			    margin-left: 15px;
			}
		</style>
	</head>
	<body>
		<?php for($i=0;$i<count($this->data);$i++) { ?>
   <div class ="spl">
       <img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-2.jpg">
       <div class ="username"><?php echo $this->data[$i]->getUsername() ?></div>
       <div class ="email"><?php echo $this->data[$i]->getEmailId() ?></div>
       <a href="confirm/id/<?php echo $this->data[$i]->getId() ?>"><button class="butn">Confirm</button></a>
       <a href="declineRequest/id/<?php echo $this->data[$i]->getId() ?>"><button class="butn">Not Now</button></a>
   </div>
	</body>
</html>