<?php
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/friends.css");
?>
    <div class ="spl">
        <img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-2.jpg">
        <div class ="username">Raghav</div>
        <div class ="email">SouthAfrica</div>
         <button class="butn">+1Add Friends</button>
    </div>
   <div class ="spl">
        <img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-3.jpg">
        <div class ="username">pathak</div>
        <div class ="email">SouthAfrica</div>
       <button class="butn">+1Add Friends</button>
    </div>
     <div class ="spl">
        <img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-4.jpg">
        <div class ="username">Sandy</div>
        <div class ="email">SouthAfrica</div>
       <button class="butn">+1Add Friends</button>
    </div>
     <div class ="spl">
        <img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-5.jpg">
        <div class ="username">Raghav</div>
        <div class ="email">SouthAfrica</div>
       <button class="butn">+1Add Friends</button>
    </div>
     <div class ="spl">
        <img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-6.jpg">
        <div class ="username">Rawat</div>
        <div class ="email">SouthAfrica</div>
       <button class="butn">+1Add Friends</button>
    </div>


