<?php
//$this->headScript()->appendFile(PUBLIC_PATH . "/js/loginpage.js");
?>
<div class="outer" style="overflow-x: hidden;" >
<div class="outer" style="width:80%; margin-left: 311px;">
  <div class="col-md-4">
    <div class="card">
      <div class="header" style="background-color: #9567D5;">
        <h4 class="title">Login</h4>
      </div>
      <div class="content" >
        <form action="/<?php echo PROJECT_NAME; ?>authenticate/login" method="post">
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="exampleInputEmail1">Email address</label>
                <input type="email" name="email" class="form-control" placeholder="Email">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group">
                <label for="exampleInputEmail1">Password</label>
                <input type="password" name="pass" class="form-control" placeholder="Password">
              </div>
            </div>
          </div>
          <div class="row">
            <div class="margin" style="width: 232px; float: left; margin-left: 103px;">
              <button type="submit" style="height:39px;width:315px" class="btn btn-info btn-fill pull-right">Login</button>
            </div>
          </div>
        </form>
        <div style="width: 100%; height: 14px; border-bottom: 1px solid grey; text-align: center">
          <span style="font-size: 15px; background-color: white; padding: 0 10px;">New to UserManagement?</span>
        </div>
        <div class="row">
          <div class="margin" style="width: 241px; float: left; margin-left: 92px;margin-top:8px;">
            <a href="authenticate/register"><button class="btn btn-info btn-fill pull-right" style="width: 315px">Create New Account </button></a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>