<!DOCTYPE html>
<html>
  <head>
    <script>
      $(function() {
      $("form[name='index']").validate({
      rules: {
      email_id: {
      required: true
      },
      pwd: {
      required: true
      }
      },
      messages: {
      email_id: {
      required: "specify email"
      },
      pwd: {
      required: "specify password"
      }
      },
      submitHandler: function(index) {
      form.submit();
      }
      });
      });
    </script>
    <style >
      form .error 
      {
      color: #F2552C;
      }
    </style>
  </head>
  <div class="outer"style="overflow-x: hidden;" >
    <div class="outer" style="width: 90%; margin-left: 174px;">
     <div class="col-md-5">
         <div class="card">
             <div class="header" style="background-color: #9567D5;">
                 <h4 class="title">Login</h4>
             </div>
             <div class="content" >
                 <form action="/<?php echo PROJECT_NAME; ?>authenticate/login" method="post" name="index">
                     <div class="row">
                         <div class="col-md-12">
                             <div class="form-group">
                                 <label for="exampleInputEmail1">Email address</label>
                                 <input type="email" name="email_id" class=
                                 "form-control" placeholder="Email">
                             </div>
                         </div>
                     </div>
                     <div class="row">
                         <div class="col-md-12">
                             <div class="form-group">
                                 <label for="exampleInputEmail1">Password</label>
                                 <input type="password" name="pwd" class="form-control" placeholder="Password">
                             </div>
                         </div>
                     </div>
                     <div class="row">
                         <div class="margin" style="width: 222px; float: left; margin-left: 103px;">
                             <button type="submit" style="height:39px;width:308px" class="btn btn-info btn-fill pull-right" name="submit">Login</button>
                         </div>
                     </div>
                 </form>
                 <div style="width: 100%; height: 14px; border-bottom: 1px solid grey; text-align: center">
                     <span style="font-size: 15px; background-color: white; padding: 0 10px;">New to UserManagement?</span>
                 </div>
                 <div class="row">
                     <div class="margin" style="width: 309px; float: left; margin-left: 16px;margin-top:8px;">
                         <a href="authenticate/register"><button class="btn btn-info btn-fill pull-right" style="width: 308px">Create New Account </button></a>
                     </div>
                 </div>
             </div>
         </div>
     </div>
  </div>
</html>