<!DOCTYPE html>
<html>
    <head>
        <script >
            $(function() {
            $("form[name='register']").validate({
            rules: {
            fname:    "required",
            lname:    "required",
            username: "required",
            email_id: {
            required: true,
            email:    true
            },
            password: {
            required: true,
            minlength: 7
            }
            },
            messages: {
            username:  "Please enter your username",
            password: {
            required:  "Please provide a password",
            minlength: "Your password must be at least 7 characters long"
            },
            email_id:  "Please enter a valid email address"
            },
            submitHandler: function(register) {
            form.submit();
            }
            });
            });
        </script>
        <style >
            form .error 
            {
              color: #F2552C;
            }
        </style>
    </head>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <div class="card">
                    <div class="header">
                        <h4 class="title">Registration</h4>
                    </div>
                    <div class="content">
                        <form action="add" method="post" name="register">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for ="fname" >FirstName</label>
                                        <input type="text" class="form-control"  placeholder="FirstName" name="fname" size="12">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>LastName</label>
                                        <input type="text" class="form-control" placeholder="LastName" name="lname" >
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>UserName</label></br>
                                        <input type="text" class="form-control" placeholder="UserName" name="username" >
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" class="form-control" name="password" id="password" placeholder="&#9679;&#9679;&#9679;&#9679;&#9679;">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label>Email ID</label>
                                        <input type="email" class="form-control" placeholder="singh@sandeep.com " name="email_id">

                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label>Status</label>
                                        <textarea rows="5" class="form-control" placeholder="Here can be your status" name="status"></textarea>
                                    </div>
                                </div>
                            </div> 
                            <button type="submit" class="btn btn-info btn-fill pull-center" name="submit">Save Form</button>
                            <div class="clearfix"></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</html>
 