<?php
$this->headTitle()->prepend('view');
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/grid.css");
?>

<!DOCTYPE html>
<html>
<body>
<?php for($i=0;$i<count($this->data);$i++) { ?>
<div class="img">
    <img id = "myImg" src="<?php echo IMAGE_PATH ?>/<?php echo $this->data[$i]->getPhoto(); ?>"  />
   <div class="desc"><?php echo $this->data[$i]->getDescription(); ?></div>
</div>
 <?php } ?>

<div id="myModal" class="modal">
  <span class="close">X</span>
  <img class="modal-content" id="img01">
  <div id="caption"></div>
</div>

<script>
var modal = document.getElementById('myModal');
var img = document.getElementById('myImg');
var modalImg = document.getElementById("img01");
var captionText = document.getElementById("caption");
img.onclick = function(){
    modal.style.display = "block";
    modalImg.src = this.src;
    captionText.innerHTML = this.alt;
}
var span = document.getElementsByClassName("close")[0];
span.onclick = function() { 
    modal.style.display = "none";
}
</script>
</body>
</html>

