<?php
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/album.css");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/frontend/album.js");
?>



<div id = "container">
        <div id = "main">
            <div class = "Row">
              <div class="Colomn">
                <a href="#">
                  <img src="<?php echo IMAGE_PATH ?>/static/faces/face-3.jpg" class="Img" > 
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>
              <div class="Colomn">
                <a href="#">
                <img src="" class="Img" >            
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>          
              <div class= "Colomn">
                <a href="#">
                <img src="" class="Img" >
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>
            </div>

            <div class = "Row">
              <div class="Colomn">
                <a href="#">
                  <img src="" class="Img" > 
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>
              <div class="Colomn">
                <a href="#">
                <img src="" class="Img" >            
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>          
              <div class= "Colomn">
                <a href="#">
                <img src="" class="Img" >
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>
            </div>

            <div class = "Row">
              <div class="Colomn">
                <a href="#">
                  <img src="" class="Img" > 
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>
              <div class="Colomn">
                <a href="#">
                <img src="" class="Img" >            
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>          
              <div class= "Colomn">
                <a href="#">
                <img src="" class="Img" >
                <div class="Info-album">
                  <b>Name:</b><?php echo $this->data->getName()?><br>
                  <b>Location:</b><?php echo $this->data->getLocation()?><br>
                  <b>Description:</b><?php echo $this->data->getDescription()?><br>
                  <b>Created At:</b><?php echo $this->data->getCreatedAt()->format("d/m/Y")?><br>
                </div>
                </a>
              </div>
            </div>
        </div>
        <button id="but" offset='9'>Show More</button>
    </div>

               