
<div class="container-fluid">
   <div class="row">
       <div class="col-md-8">
           <div class="card">
               <div class="header">
                   <h4 class="title">Create Album</h4>
               </div>
               <div class="content">
                   <form action="/<?php echo PROJECT_NAME; ?>album/add" method="post">
                                             <div class="row">
                           <div class="col-md-6">
                               <div class="form-group">
                                   <label>Album Name</label>
                                   <input type="text" name="name" class="form-control" placeholder="name" >
                               </div>
                           </div>
                           <div class="row">
                           <div class="col-md-6">
                               <div class="form-group">
                                   <label>Location</label>
                                   <input type="text" name="location" class="form-control" placeholder="Location">
                               </div>
                           </div>
                       </div>
                       </div>                        <div class="row">
                           <div class="col-md-12">
                               <div class="form-group">
                                   <label>Description</label>
                                   <textarea rows="5" class="form-control" placeholder="Here can be your description" name="desc"></textarea>
                               </div>
                           </div>
                       </div><br>                        
                       <button type="submit" class="btn btn-info btn-fill pull-left">Submit</button>
                       <div class="clearfix"></div>
                   </form>
               </div>
           </div>
        </div>

