<?php
/**
* Created by sublime.
* User: KaurHarjinder
* Date: 9/22/2016
* Time: 10:11 AM
*/
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/album.css");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/frontend/album.js");
?>

<!-- Hidden id of user and print its value-->
<input type='hidden' id='user_id' value="<?php echo $this->user_id ?>">
<!-- Content Starts -->
  <div id = "container">
    <div id = "main">

    </div>
  </div>




