<div class="albumout" style="float:left; width: 900px; ">
<?php for($i=0;$i<count($this->result);$i++) { ?>
<div class="albumclass" style='background-color: #946bd5;
    border: 1px solid;
    border-radius: 82px;
    height: 120px;
    width: 123px;
    width: 123px; 
    margin: 20px;
    float: left;'>
    <a href="gallery/albumId=<?php echo $this->result[$i]->getId() ?>">
        <div id="albumtxt" style="margin-top: 45px;
    text-align: center;">
        <span><?php echo $this->result[$i]->getName() ?></span>
        </div>
    </a>
</div>
<?php } ?>
</div>