<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <noscript>Your browser does not support JavaScript!</noscript>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport'/>
        <meta name="viewport" content="width=device-width"/>
        <?php
        $this->headLink()->headLink(array('rel' => 'icon', 'href' => PUBLIC_PATH . '/images/static/user-management.png'), 'PREPEND');
        $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html; charset=utf-8')->appendHttpEquiv('Content-Language', 'en-UK');
        $this->headMeta()->appendName('description', 'This is a project development for training purpose. So that trainee devs can get knowledge about ZF 1 and git.');
        $this->headMeta()->appendName('keywords', '');

        //CSS
        $this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/style.css");
        $this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/bootstrap.min.css");
        $this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/animate.min.css");
        $this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/light-bootstrap-dashboard.css");
        $this->headLink()->appendStylesheet('http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css');
        $this->headLink()->appendStylesheet('http://fonts.googleapis.com/css?family=Roboto:400,700,300');
        $this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/pe-icon-7-stroke.css");

        //JS
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/common.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/frontend/light-bootstrap-dashboard.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/constants.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/date.js");
        $this->headScript()->prependFile('https://maps.googleapis.com/maps/api/js?sensor=false');
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/bootstrap-notify.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/chartist.min.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/bootstrap-checkbox-radio-switch.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/bootstrap.min.js");
        $this->headScript()->prependFile("https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.1/jquery.validate.min.js");
        $this->headScript()->prependFile(PUBLIC_PATH . "/js/jquery-1.10.2.js");

        echo $this->headTitle();
        echo $this->headMeta();
        echo $this->headLink();
        echo $this->headScript();

        $params = Zend_Controller_Front::getInstance()->getRequest()->getParams();
        ?>

    </head>
    <body>
        <div class="wrapper">
             <?php if($params['controller'] != 'authenticate' && $params['controller'] != 'request' ) { ?>
        <div class="sidebar" data-color="purple" data-image="<?php echo IMAGE_PATH ?>/static/sidebar-5.jpg">

                <!--   you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple" -->

                <div class="sidebar-wrapper">
                    <div class="logo">
                        <a href="http://www.creative-tim.com" class="simple-text">
                            Creative Tim
                        </a>
                    </div>

                    <ul class="nav">
                        <li <?php if($params['controller'] == 'index'): echo 'class="active"'; endif; ?> >
                            <a href="/<?php echo PROJECT_NAME; ?>index/index">
                                <i class="pe-7s-graph"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                        <li <?php if($params['controller'] == 'profile'): echo 'class="active"'; endif; ?> >
                            <a href="/<?php echo PROJECT_NAME; ?>profile/index">
                                <i class="pe-7s-user"></i>
                                <p>User Profile</p>
                            </a>
                        </li>
                        <li <?php if($params['controller'] == 'album' && $params['controller'] != 'request'): echo 'class="active"'; endif; ?> >
                            <a href="/<?php echo PROJECT_NAME; ?>album/index">
                                <i class="pe-7s-album"></i>
                                <p>Create Album</p>

                            </a>
                        </li>
                        
                        <li <?php if($params['controller'] == 'photo'): echo 'class="active"'; endif; ?> >
                            <a href="/<?php echo PROJECT_NAME; ?>photo/index">
                                <i class="pe-7s-photo"></i>
                                <p>Photo Page</p>

                            </a>
                        </li>
                        
                    </ul>
                </div>
            </div>
          <?php } ?>

            <div class="main-panel" style="background-color: white;">
                <?php if($params['controller'] != 'authenticate' && $params['controller'] != 'request') { ?>
                <nav class="navbar navbar-default navbar-fixed">
                    <div class="container-fluid">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse"
                                    data-target="#navigation-example-2">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                            <a class="navbar-brand" href="#">Table List</a>
                        </div>
                        <div class="collapse navbar-collapse">
                            <ul class="nav navbar-nav navbar-left">
                                <li>
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-dashboard"></i>
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        <i class="fa fa-globe"></i>
                                        <b class="caret"></b>
                                        <span class="notification">5</span>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Notification 1</a></li>
                                        <li><a href="#">Notification 2</a></li>
                                        <li><a href="#">Notification 3</a></li>
                                        <li><a href="#">Notification 4</a></li>
                                        <li><a href="#">Another notification</a></li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="">
                                        <i class="fa fa-search"></i>
                                    </a>
                                </li>
                            </ul>

                            <ul class="nav navbar-nav navbar-right">
                                <li>
                                    <a href="">
                                        Account
                                    </a>
                                </li>
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                        Dropdown
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">Action</a></li>
                                        <li><a href="#">Another action</a></li>
                                        <li><a href="#">Something</a></li>
                                        <li><a href="#">Another action</a></li>
                                        <li><a href="#">Something</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">Separated link</a></li>
                                    </ul>
                                </li>
                                <li>
<!--                                    todo use PROJECT_URL and PROJECT_NAME for forming URL.
                                        todo example '<a href="<?php //echo PROJECT_URL.'/'.PROJECT_NAME;?>page/help">Help</a>'
-->
                                     <a href="<?php echo $this->baseUrl('/authenticate/logout'); ?>">Logout</a>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
                <?php } ?>

          



                <div class="content">
                    <?php
                    echo $this->layout()->content;
                    ?>
                </div>
                <?php
                //print_r($params); die;
                if($params['controller'] != 'authenticate' && $params['controller'] != 'request')
                    {
                ?>
                <footer class="footer">
                    <div class="container-fluid">
                        <nav class="pull-left">
                            <ul>
                                <li>
                                    <a href="#">
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Company
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Portfolio
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
                                        Blog
                                    </a>
                                </li>
                            </ul>
                        </nav>
                        <p class="copyright pull-right">
                            &copy; 2016 <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                        </p>
                    </div>
                </footer>
                <?php
                }
                ?>
            </div>
        </div>
    </body>
</html>