<?php
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/friends.css");
 ?>
<div id ="outerblock">
	<div class ="inersrc">
		<img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-2.jpg">
		<img src ="http://localhost/friends-gallary-zf1/public/images/static/faces/face-3.jpg">
		<div class ="username">Username</div>
		<div class ="email">Email</div>
		<button class="pe-7e-close-circle"></button>
		<button class="pe-7s-add-user"></button>
	</div>
