<?php
$this->headTitle()->prepend('Registration');
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/user.css");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/frontend/user.js");

?>

<!-- Content Starts -->
<div class="container-fluid"> 
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="header">

                    <h4 class="title">Registration</h4>
                </div>
                <div class="content">
                    <form action="add" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>FirstName</label>
                                    <input type="text" class="form-control"  placeholder="FirstName" name="fname">
                                           
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>LastName</label>
                                    <input type="text" class="form-control" placeholder="LastName" name="lname" >
                                </div>
                            </div>
                           
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>UserName</label></br>
                                    <input type="text" class="form-control" placeholder="UserName" name="username" >
                                   
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="Password" class="form-control" placeholder="Password" name="pwd" >
                                </div>
                            </div>
                        </div>
                         <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email ID</label>
                                    <input type="email" class="form-control" placeholder="Email id " name="email_id">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Status</label>
                                    <textarea rows="5" class="form-control" placeholder="Here can be your status"
                                              name="status"></textarea>
                                </div>
                            </div>
                        </div>

                        <button type="submit" class="btn btn-info btn-fill pull-center" name="submit">Save Form</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
       
        <div class="col-md-4">
            <div class="card card-user">
                <div class="image">
                    <img
                        src="https://ununsplash.imgix.net/photo-1431578500526-4d9613015464?fit=crop&fm=jpg&h=300&q=75&w=400"
                        alt="..."/>
                </div>
                <div class="content">
                    <div class="author">
                        <a href="#">
                            <img class="avatar border-gray" src="<?php echo IMAGE_PATH ?>/static/faces/face-3.jpg" alt="..."/>

                            <h4 class="title"><br/>
                                <small></small>
                            </h4>
                        </a>
                    </div>
                    <p class="description text-center"><br><br>
                    </p>
                </div>
                <hr>
                <div class="text-center">
                    <button href="#" class="btn btn-simple"><i class="fa fa-facebook-square"></i></button>
                    <button href="#" class="btn btn-simple"><i class="fa fa-twitter"></i></button>
                    <button href="#" class="btn btn-simple"><i class="fa fa-google-plus-square"></i></button>

                </div>
            </div>
        </div>

    </div>
</div>


                    
                            
    

