<?php

/**
* Created by sublime.
* User: singhSandeep
* Date: 9/22/2016
* Time: 3:01 PM
*/

$this->headTitle()->prepend('Registration');
$this->headLink()->appendStylesheet(PUBLIC_PATH . "/css/frontend/user.css");
$this->headScript()->appendFile(PUBLIC_PATH . "/js/frontend/user.js");
?> 

<!-- Content Starts -->

<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="header">
                    <h4 class="title">Registration</h4>
                </div>
                <div class="content">
                    <form action="add" method="post">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>FirstName</label>
                                    <input type="text" class="form-control"  placeholder="FirstName" name="fname">
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>LastName</label>
                                    <input type="text" class="form-control" placeholder="LastName" name="lname" >
                                </div>
                            </div>                       

                        </div>

 

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>UserName</label></br>
                                    <input type="text" class="form-control" placeholder="UserName" name="username" >
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="Password" class="form-control" placeholder="Password" name="pwd" >
                                </div>
                            </div>
                        </div>

                         <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Email ID</label>
                                    <input type="text" class="form-control" placeholder="Email id " name="email_id">
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label>Status</label>
                                    <textarea rows="5" class="form-control" placeholder="Here can be your description" name="status"></textarea>
                                </div>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-info btn-fill pull-center" name="submit">Save Form</button>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

 